// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB98aAvQQGJzCMSigr_33xLsFbNhAKVPIs',
    appId: '1:1066560007292:web:288ce350dd937af0d6edf9',
    messagingSenderId: '1066560007292',
    projectId: 'biznetize-5ea34',
    authDomain: 'biznetize-5ea34.firebaseapp.com',
    storageBucket: 'biznetize-5ea34.appspot.com',
    measurementId: 'G-P56302L135',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfmbs0LDxwwW2rcouPkZOCXcKoC0cMbXM',
    appId: '1:1066560007292:android:7134423b72c3348dd6edf9',
    messagingSenderId: '1066560007292',
    projectId: 'biznetize-5ea34',
    storageBucket: 'biznetize-5ea34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqJb6jrJCm2a7SUC-ZFxmN3J2I3PUT7PU',
    appId: '1:1066560007292:ios:cdd8b0f97f6899d5d6edf9',
    messagingSenderId: '1066560007292',
    projectId: 'biznetize-5ea34',
    storageBucket: 'biznetize-5ea34.appspot.com',
    iosBundleId: 'com.example.bizissue',
  );
}
